title: "Portafolio de Data Engineering4"
description: "Guías técnicas y arquitecturas de datos"
remote_theme: "pmarsceill/just-the-docs"

# Esto le dice al tema cómo comportarse
just_the_docs:
  search_enabled: true
  nav_sort: nav_order
  # Esta es la variable nativa del tema para el ancho
  sidebar_width: 200px 

docs_dir: docs
